image:
  - Visual Studio 2022
  - Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
#  APPVEYOR_RDP_PASSWORD: "/@}D9G7+mXRQNaqV"

skip_commits:
  files:
    - '**/*.md'

build: off

#before_test:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # windows only because of APPVEYOR_YML_DISABLE_PS_LINUX https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
  - ps: Install-Module Pester -RequiredVersion 6.0.0 -Force -SkipPublisherCheck
  # linux only
  - sh: git clone https://github.com/bats-core/bats-core.git
  - sh: pushd bats-core
  - sh: export PATH=$PATH:$HOME/bin
  - sh: ./install.sh $HOME
  - sh: popd

test_script:
  # windows only because of APPVEYOR_YML_DISABLE_PS_LINUX https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
  - ps: |
      $testResultsFile = ".\TestsResults.xml"

      $config = New-PesterConfiguration
      $config.Run.Path = ".\tests"
      $config.Run.PassThru = $true
      
      $config.TestResult.Enabled = $true
      $config.TestResult.OutputFormat = "NUnitXml"
      $config.TestResult.OutputPath = $testResultsFile
      
      $res = Invoke-Pester -Configuration $config
      
      $resultsUploadUrl = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      
      (New-Object 'System.Net.WebClient').UploadFile(
          $resultsUploadUrl,
          (Resolve-Path $testResultsFile)
      )
      
      if ($res.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }
  # checks if code from documentation ok
  - ps: iwr -useb https://raw.githubusercontent.com/boxforming/base/master/scripts/access-controller.psm1 | iex
  - ps: New-ClientAuthCert -Username test
  # linux only
  - sh: bats tests
  # checks if code from documentation ok
  - sh: source <(cat scripts/boxforming.sh)
  - sh: new_client_auth_cert
